# Generated by Django 6.1.1 on 2026-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('dead_stock', 'Dead Stock'), ('mpesa_failed', 'M-Pesa Failed'), ('system_error', 'System Error')], max_length=64)),
                ('message', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('dedupe_key',), name='uniq_notification_dedupe_key')],
            },
        ),
    ]
