# Generated by Django 6.1.1 on 2026-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mpesa_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('voided_count', models.IntegerField(default=0)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('top_products', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
